version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - scbuildcodeunits
    aliases:
      - basebuildallcodeunits
      - bb

  GryvaicecastserverRunExample:
    desc: "GRYVAIcecastServer: Run example"
    silent: true
    dir: "./GRYVAIcecastServer/Other/Examples/MinimalDockerComposeFile"
    cmds:
      - python3 RunExample.py
    aliases:
      - gryvaicecastserverrunexample
