version: '3.2'

services:
  gryvaicecastserver:
    image: 'gryvaicecastserver:0.2.1'
    container_name: 'gryvaicecastserver'
    volumes:
      - "./Volumes/Data:/root/.bitcoin"
      - "./Volumes/Log:/var/log/tor"
